language: node_js
sudo: false
cache:
  apt: true
  directories:
  - node_modules
node_js:
- 6.9.0
branches:
  only:
  - hexo
before_install:
- openssl aes-256-cbc -K $encrypted_b6a9c7fbd133_key -iv $encrypted_b6a9c7fbd133_iv -in .travis/coding_net_rsa.enc -out ~/.ssh/coding_net_rsa -d
- openssl aes-256-cbc -K $encrypted_b6a9c7fbd133_key -iv $encrypted_b6a9c7fbd133_iv -in .travis/github_rsa.enc -out ~/.ssh/github_rsa -d
- chmod 600 ~/.ssh/coding_net_rsa
- chmod 600 ~/.ssh/github_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/github_rsa
- ssh-add ~/.ssh/coding_net_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "Jinlong Quan"
- git config --global user.email "ovwane@gmail.com"
install:
- npm install hexo-cli -g
- npm install hexo-deployer-git --save
- npm install
- git clone https://github.com/ovwane/ovwane.github.io .deploy_git
- cd .deploy_git && git checkout master
- cd ..
script:
- hexo clean
- hexo generate
- hexo deploy
after_success:
- echo "OK!网站部署成功啦！"
