language: node_js

sudo: false

cache:
  apt: true
  directories:
  - node_modules

node_js:
  - 8.11.3

branches:
  only:
  - hexo

before_install:
- export TZ='Asia/Shanghai'
- openssl aes-256-cbc -K $encrypted_40dbd9c24c4f_key -iv $encrypted_40dbd9c24c4f_iv
  -in .travis/hexo_rsa.enc -out ~/.ssh/hexo_rsa -d
- chmod 600 ~/.ssh/hexo_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/hexo_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "Jinlong Quan"
- git config --global user.email "ovwane@gmail.com"

install:
- npm install hexo-cli -g
- npm install hexo-deployer-git --save
- npm install
- git clone https://github.com/ovwane/ovwane.github.io .deploy_git
- cd .deploy_git && git checkout master
- cd ..

script:
- git submodule init      # 用于更新主题,更新源为自己的主题项目。
- git submodule update
- hexo clean
- hexo generate
- hexo deploy

after_success:
- echo "OK!网站部署成功啦！"
